Accounts/urls.py
from django.urls import path
from .views import *
app_name='Accounts'
urlpatterns = [
 path('login', login_view ,name='login'),
 path('register', register_view, name='register'),
 path('logout', logout_view, name='logout'),

]

home/urls.py
from django.urls import path
from .views import *
app_name='home'
urlpatterns = [
 path('', home_view,name='home'),
]

post/urls.py
from django.urls import path
from .views import *
app_name='post'
urlpatterns = [
 path('index', post_index , name='index'),
 path('<int:id>', post_detail,name='detail'),
 path('create', post_create,name='create'),
 path('<int:id>/update',post_update,name='update'),
 path('<int:id>/delete', post_delete,name='delete'),
]

yazlab3/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import  static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('post/',include("post.urls")),
    path('accounts/', include("Accounts.urls")),

]
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/views.py
from django.shortcuts import render

# Create your views here.
def home_view(request):
    context = {

    }
    return render(request,'home.html',context)

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
     <nav class="navbar sticky-top navbar-dark text-light bg-dark navbar-expand " >
      <div class="container-fluid">
         <a class="navbar-brand" href="{% url 'home:home' %}">Anasayfa</a>
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
           <div class="navbar-nav">
               {% if request.user.is_authenticated %}
             <a class="nav-link active" aria-current="page" href="{% url 'post:index' %}">Postlar</a>
             <a class="nav-link" href="{% url 'post:create' %}">Post Oluştur</a>
              {% endif %}
                   {% if not request.user.is_authenticated %}
             <a class="nav-link active" aria-current="page" href="{% url 'Accounts:login' %}">Giriş Yap</a>
               {% else %}
                   <a class="nav-link active" aria-current="page" href="{% url 'Accounts:logout' %}">Çıkış Yap</a>
               {% endif %}
           </div>
         </div>

      </div>
    </nav>


    {% block body %}

    {% endblock %}

<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block body %}

 <b>Giriş Yaparak Post Ekleme ve Düzenleme Yapabilirsiniz</b>

{% endblock %}